language: php

php:
  - 5.5

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  vendor/bin/phpunit tests

addons:
  ssh_known_hosts: vps.jmgpena.net

before_install:
- openssl aes-256-cbc -K $encrypted_1f469ef81ca4_key -iv $encrypted_1f469ef81ca4_iv -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key

after_success:
- rsync -rv --delete -e "ssh -i deploy_key" vendor jmgpena@vps.jmgpena.net:~/cfc/vendor
- rsync -rv --delete -e "ssh -i deploy_key" public jmgpena@vps.jmgpena.net:~/cfc/public
